### PR TITLE
Removes deferred sections from Wiki and adds testing instructions to Getting Started.

### PR DESCRIPTION
**Pull request by brianlombardo**
## Checklist:
- [ ] Is the linter reporting 0 errors?
- [ ] Did you comply with our [styleguide](https://github.com/wwt/Workflow/blob/main/STYLEGUIDE.md)?
- [ ] Is there [adequate test coverage](https://github.com/wwt/Workflow/blob/main/CONTRIBUTING.md#test-etiquette) for your new code?
- [ ] Does the CI pipeline pass?
- [ ] Is the [static analysis tool](https://sonarcloud.io/dashboard?id=wwt_Workflow) reporting 0 issues?
- [x] Did you [update the documentation](https://github.com/wwt/Workflow/blob/main/CONTRIBUTING.md#documentation)?
- [ ] Did you [update the sample app](https://github.com/wwt/Workflow/blob/main/CONTRIBUTING.md#sample-app)?
- [ ] Do we need to [increment the minor/major version](https://github.com/wwt/Workflow/blob/main/CONTRIBUTING.md#versioning)?
- [ ] Did you [change the public API](https://github.com/wwt/Workflow/blob/main/CONTRIBUTING.md#public-api)?
- [ ] Have you done everything you can to make sure that errors that can occur are compile-time errors, and if they have to be runtime do you have adequate tests and documentation around those runtime errors? [For more details](https://github.com/wwt/Workflow/blob/main/CONTRIBUTING.md#errors).

----

### If Applicable:
- [ ] Did you test when the first item is skipped?
- [ ] Did you test when the last item is skipped?
- [ ] Did you test when middle items are skipped?
- [ ] Did you test when incorrect data is passed forward?
- [ ] Did you test proceeding backwards?

----

### If Public API Has Changed:
- [ ] Did you deprecate (rather than remove) any old methods/variables/etc? [Our philosophy for deprecation](https://github.com/wwt/Workflow/blob/main/CONTRIBUTING.md#deprecation).
- [ ] Have you done the best that you can to make sure that the compiler guides people to changing to the new API? (Example: the renamed attribute)
- [ ] If necessary, have you tested the upgrade path for at least N-1 versions? For example, if data persists between v1 and v2 then that upgrade should be tested and as easy as we can make it.

### CODE REVIEW

**Comment by brianlombardo** [comment]
Today we looked at which wiki sections are essential for a great onboarding experience, and we started to research the needed steps for the "Testing Your Workflows" document.

We also had discussion around the necessity and content of the Tutorial.

**Comment by brianlombardo** [comment]
We decided to include testing as part of Getting Started and will add a new card for addressing FAQ, Tutorial, and Advanced sections.

**Comment by Richard-Gist** [comment]
EOD:  We decided that for testing we should only include the minimum for Getting Started, and as such we will show examples to test the SecondViewController which will cover `shouldLoad` and `proceedInWorkflow`.  We will continue to show with UIUTest as the preferred way of testing, but will have a callout of what is UIUTest specific and the overview of what we are doing.

**Review by morganzellers — APPROVED** [review]

**Review by wiemerm — APPROVED** [review]

**Review by Richard-Gist — APPROVED** [review]

**Comment by Richard-Gist** [comment]
When you finish your review @brianlombardo you are good to merge the PR.

**Pull request merged**
